-- Supabase API erişimi (RLS açıksa service_role yine de okur; anon için gerekebilir)
ALTER TABLE yonetici_kullanicilar DISABLE ROW LEVEL SECURITY;
ALTER TABLE dukkan_ayarlari DISABLE ROW LEVEL SECURITY;
ALTER TABLE musteriler DISABLE ROW LEVEL SECURITY;
ALTER TABLE tamir_kayitlari DISABLE ROW LEVEL SECURITY;
ALTER TABLE stok DISABLE ROW LEVEL SECURITY;
ALTER TABLE tedarikciler DISABLE ROW LEVEL SECURITY;
ALTER TABLE tedarikci_islemleri DISABLE ROW LEVEL SECURITY;
ALTER TABLE finans_islemleri DISABLE ROW LEVEL SECURITY;
ALTER TABLE garantiler DISABLE ROW LEVEL SECURITY;
ALTER TABLE pos_satislar DISABLE ROW LEVEL SECURITY;
ALTER TABLE pos_satis_kalemleri DISABLE ROW LEVEL SECURITY;
ALTER TABLE cari_islemleri DISABLE ROW LEVEL SECURITY;
