-- Supabase API erişimi (RLS açıksa service_role yine de okur; anon için gerekebilir)
ALTER TABLE admin_users DISABLE ROW LEVEL SECURITY;
ALTER TABLE shop_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE repairs DISABLE ROW LEVEL SECURITY;
ALTER TABLE inventory DISABLE ROW LEVEL SECURITY;
ALTER TABLE suppliers DISABLE ROW LEVEL SECURITY;
ALTER TABLE supplier_transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE warranties DISABLE ROW LEVEL SECURITY;
ALTER TABLE pos_sales DISABLE ROW LEVEL SECURITY;
ALTER TABLE pos_sale_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE customer_transactions DISABLE ROW LEVEL SECURITY;
